/* IN SOME OF THE COLUMNS LIKE (TOTAL LAID OFF) AND (PERCENTAGE LAID OFF) BOTH OF THEM ARE WITH NULL VALUES. 
IF BOTH OF THOSE VALUES ARE NULL, THEY ARE USELESS FOR US SINCE THE DATASET IS  ABOUT LAID OFFS AND THAT IS THE INFO WE WORK WITH.

WE ARE GOING TO GET RID OF THOSE ROWS AS WE CAN'T GET MUCH INTEL FROM THEM.*/

SELECT *
FROM layoffs_staging2
WHERE total_laid_off IS NULL 
    AND percentage_laid_off IS NULL;

DELETE 
FROM layoffs_staging2
WHERE total_laid_off IS NULL 
    AND percentage_laid_off IS NULL;

